SELECT TITLE, B.BOARD_ID AS BOARD_ID, REPLY_ID,
       R.WRITER_ID AS WRITER_ID, R.CONTENTS AS CONTENTS, 
       DATE_FORMAT(R.CREATED_DATE, '%Y-%m-%d') AS CREATED_DATE
FROM USED_GOODS_BOARD AS B JOIN USED_GOODS_REPLY AS R
ON B.BOARD_ID = R.BOARD_ID
WHERE MONTH(B.CREATED_DATE) = 10
ORDER BY R.CREATED_DATE ASC, B.TITLE ASC;